import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div></div>
        </div>

        <div className={styles.center}>
          <h1 className={styles.top}>Andrew McCulley</h1>
        </div>
        <div>
          <a
            href="https://github.com/amcculley222"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img
              className={styles.logo}
              src="/github.svg"
              alt="Github.js Logo"
              width={180}
              height={37}
              priority
            />
          </a>
          <a
            href="https://www.linkedin.com/in/mcculleyandrew/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <img
              className={styles.logo}
              src="/linkedin.svg"
              alt="LinkedIn.js Logo"
              width={180}
              height={37}
              priority
            />
          </a>
        </div>

        <div className={styles.grid}>
          <a
            href="https://github.com/amcculley222/Project2-AM"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              AUX Project<span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              full stack web application that allows user to create a playlist
              and then shuffle based on a mood
            </p>
          </a>

          <a
            href="https://amcculley222.github.io/Blackjack-Project1/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              BlackJack Project <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Interactive Blackjack game using JavaScript, HTML, and CSS
            </p>
          </a>

          <a
            href="https://github.com/amcculley22/Project4"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Project 4 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Final project full stack application
            </p>
          </a>

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a> */}
        </div>
      </main>
    </>
  );
}
